### ISSUE TITLE
Add issue tracker's support 

### ISSUE THREAD

**Issue by w32blaster** [w32blaster/revizor#2]
Add interface and different realizations for issues trackers. Revizor should be able to scan a commit description and extract URL or Key of an assigned ticket. The link should appear in a review description.
## Dod:
- [x] if [Smart Commits](https://github.com/w32blaster/revizor/wiki/Smart-commits) are presented in a comment description, then:
  - [x] an upcoming review should be associated with the given Issue
  - ~~the **header** and **description** should be pre-filled when an user creates a new review~~
  - [x] the Issue itself should be modified: in simpliest case append to its description link to review. 
    Otherwise some trackers (like Jira) have special link for a code reviews.
- [x] an user should have opportunity to assign manually any Issue to already existing Review
- [x] when some actions happen in a review (approve/disapprove, closing, comments) then an appropriate comment should appear under the associated Issue.
- [x] add cache to the remote calling
## Issue trackers to be supported:
- Jira
- YouTrack
- GitHub Issue Tracker
- BitBucket
