### ISSUE TITLE
Add feature to view all the changeset without a review

### ISSUE THREAD

**Issue by w32blaster** [w32blaster/revizor#21]
At this moment there is only one possibility to view the DIFF code is to create a review. But usually managers and team leaders needs just to browse new commits without any review, just only to check it.
## Solution

Each changeset in history graph should be clikcable. When user clicks to a changeset, then opens a view that looks like a review, but it does not conain any comments, header, description and etc. User can only view DIFFs and he/she can not leave a comments.

Each page should contain a big button "Create review" that can create a review from the browsed changeset.
## ToDo:
- [ ] Create new controller that could only show the changes files
- [ ] Modify graph tree: each node should be clickable, lieading to this controller
- [ ] Modify graph tree: if any changeset has associated review, there should be icon near it
- [ ] If there any reviews associated with current changeset, they should be listed under the buttom "Create changeset"
