### ISSUE TITLE
Make possible to compare several commits

### ISSUE THREAD

**Issue by w32blaster** [w32blaster/revizor#3]
At this moment user could select only one revision in the log to create a review. Make it possible to select several reviews, for example, the whole experimental tree.

For example, Crucible uses a draggable slider to navigate through several changes

![Atlassian Cricuble uses slider to navigate within several iterations](https://www.atlassian.com//wac/software/crucible/overview/code-review-pre-commit/featureItems/01/imageBinary/FeatTour_Iterative-Pre-commit-Reviews_288w.png)
## Todo:
- [ ] store all the selected reviews in the Review domain
- [ ] think how to represent different revisions (Crucible uses slider, something [like this](http://seiyria.github.io/bootstrap-slider/)). I think, a slider is an overkill. The list of links is quite enough.
- [ ] Implement functionality of "appending" new review to existing (so called _"patches"_ or _"iterations"_). It is useful, when review result was not success. It should work like this: user appends a commit to existing closed review, this review restores its status from **closed**  to **open**, new patsh is added to the context 
- [ ] Improve **Smart Commits**. If sertain command appears in the commit message (something like `+appendToReview 14` or something like that), then the specified review changed its status (from _"closed"_, to _"reopened"_), current commit is added to its context, new notification is created
- [ ] Add new button **"Append to..."**. At this moment you can view the tree in the dashboard and click the button `[+]`. Then new commit will be created. Add some new option "Append to..." in addition to existed functionaltiy

**Comment by w32blaster** [comment]
Sliders: http://www.webresourcesdepot.com/custom-html5-range-sliders/
