### ISSUE TITLE
Implement comparison "Side by side" in the review diff-view

### ISSUE THREAD

**Issue by w32blaster** [w32blaster/revizor#8]
We have github-like review page showing diff. For some cases it would be useful to compare old version and new one side-by-side.

Something like this:
![Crusible side by side view](http://blogs.atlassian.com/news/2010/02/18/side-by-side-web-based-diff-git-svn-p4-clearcase-cvs/side-by-side-web-based-diff-git-svn-p4-clearcase-cvs-thumb-300x225.png)

## ToDo:
* [x] implement Side-To-Side view, where old and new versions of a document are displayed in two columns
* [ ] a "break" between code hunks *(when one file has several modifications, they are separated with "cut" line)* should be displayed correctly in both view modes
* [ ] old and new zones should be displayed on the save level, but not chess-like.
* [ ] if one side became shorter/longer, than another column should be compensated with empty lines without line numbers
